name: Deploy backend
on: workflow_dispatch

jobs:
  Deploy:
    uses: hanatole/calculator-deployment/.github/workflows/deploy.yml@main
    with:
      service_name: backend
      docker_image: ahagbes/calculator-backend:latest
    secrets:
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}