name: Operation workflow
on:
  - push
jobs:
  Validation:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Setup Python
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.6.5
          python-version: 3.12
      - name: Run linter
        run: uv run ruff check .